// For productsDetailFetch
export const FETCH_PRODUCT_DETAILS_REQUEST = 'FETCH_PRODUCT_DETAILS_REQUEST';
export const FETCH_PRODUCT_DETAILS_SUCCESS = 'FETCH_PRODUCT_DETAILS_SUCCESS';
export const FETCH_PRODUCT_DETAILS_FAILURE = 'FETCH_PRODUCT_DETAILS_FAILURE';

// For productsContentFetch
export const FETCH_PRODUCT_CONTENT_REQUEST = 'FETCH_PRODUCT_CONTENT_REQUEST';
export const FETCH_PRODUCT_CONTENT_SUCCESS = 'FETCH_PRODUCT_CONTENT_SUCCESS';
export const FETCH_PRODUCT_CONTENT_FAILURE = 'FETCH_PRODUCT_CONTENT_FAILURE';


// For tabsDetailFetch
export const FETCH_TAB_DETAILS_REQUEST = 'FETCH_TAB_DETAILS_REQUEST';
export const FETCH_TAB_DETAILS_SUCCESS = 'FETCH_TAB_DETAILS_SUCCESS';
export const FETCH_TAB_DETAILS_FAILURE = 'FETCH_TAB_DETAILS_FAILURE';

// For fetchFAQentries
export const FETCH_FAQ_ENTRIES_REQUEST = 'FETCH_FAQ_ENTRIES_REQUEST';
export const FETCH_FAQ_ENTRIES_SUCCESS = 'FETCH_FAQ_ENTRIES_SUCCESS';
export const FETCH_FAQ_ENTRIES_FAILURE = 'FETCH_FAQ_ENTRIES_FAILURE';

// For productWithAllDetails
export const PRODUCT_FULL_DETAIL_REQUEST = 'PRODUCT_FULL_DETAIL_REQUEST';
export const PRODUCT_FULL_DETAIL_SUCCESS = 'PRODUCT_FULL_DETAIL_SUCCESS';
export const PRODUCT_FULL_DETAIL_FAILURE = 'PRODUCT_FULL_DETAIL_FAILURE';
